baseurl = "https://esaezgil.com/"
title = "Enrique Saez"
languageCode = "en-us"
theme =  "beautifulhugo"

PygmentsCodeFences = true
pygmentsuseclasses = false
pygmentsStyle = "manni"

CanonifyUrls = true
relativeURLs = true

disqusShortname = "esaezgil"
googleAnalytics = "UA-86132389-1"
enableRobotsTXT = true


[Params]
  description = "Enrique Saez Gil personal blog - python, software, books, open source, events"
  subtitle = "Software & Telecom engineer - ICT enthusiast"
  logo = "img/icon.jpg"
  comments = true

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    identifier = "events"
    name = "Events"
    weight = 3

[[menu.main]]
    parent = "events"
    name = "Hackathons"
    url = "/events/"
    weight = 1

[[menu.main]]
    parent = "events"
    name = "Talks"
    url = "/talks/"
    weight = 2

[[menu.main]]
    parent = "events"
    name = "Meetups"
    url = "/meetups/"
    weight = 3

[[menu.main]]
    identifier = "more"
    name = "More"
    weight = 4

[[menu.main]]
    parent = "more"
    name = "Books"
    url = "/books/"
    weight = 2

[[menu.main]]
    parent = "more"
    name = "Now"
    url = "/now/"
    weight = 2

[[menu.main]]
    parent = "more"
    name = "Links"
    url = "/interesting_links/"
    weight = 3

[Author]
  name = "Enrique Saez Gil"
  github = "esaezgil"
  twitter = "eqirn"
  linkedin = "in/enriquesaezgil/en"
  stackoverflow = "/users/4378118/enrique-saez/"
  keybase = "esaezgil"
