baseurl = "https://esaezgil.com/"
title = "Hej, I'm Enrique"
subtitle = "Software & Telecom engineer - ICT enthusiast"
languageCode = "en-us"
theme =  "beautifulhugo"
PygmentsCodeFences = true
pygmentsuseclasses = false
pygmentsStyle = "manni"

CanonifyUrls = true

disqusShortname = "esaezgil"

[Params]
  subtitle = "Software & Telecom engineer - ICT enthusiast"
  logo = "img/icon.jpg"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/enrique/"
    weight = 1

[[menu.main]]
    name = "Talks"
    url = "/page/talks/"
    weight = 2

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 1

[[menu.main]]
    name = "Books"
    url = "/page/books/"
    weight = 1

[Author]
  name = "Enrique Saez"
  github = "esaezgil"
  twitter = "eqirn"
  linkedin = "in/enriquesaezgil/en"
  stackoverflow = "4378118/enrique"
