baseurl = "https://esaezgil.github.io/"
title = "Think-Release"
subtitle = "Documenting my learning journey"
languageCode = "en-us"
theme =  "beautifulhugo"
PygmentsCodeFences = true
pygmentsuseclasses = false
pygmentsStyle = "manni"

CanonifyUrls = true

[Params]
  subtitle = "Documenting my learning journey"
  logo = "img/icon.jpg"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/enrique/"
    weight = 1

[[menu.main]]
    name = "Talks"
    url = "/page/talks/"
    weight = 2

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 1

[Author]
  name = "Enrique Saez"
  github = "esaezgil"
  twitter = "eqirn"
  linkedin = "in/enriquesaezgil/en"
  stackoverflow = "4378118/enrique"
