baseurl = "https://username.github.io"
languageCode = "en-us"
title = "Beautiful Hugo"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Build a beautiful and simple website in minutes"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false
  dateFormat = "January 2, 2006"

[[Params.bigimg]]
  src = "img/path.jpg"
  desc = "Path"

# if you add more than one bigimg they will cycle through every 10 seconds
#[[Params.bigimg]]
#  src = "img/path.jpg"
#  desc = "Another Path"

[Author]
  name = "Some Person"
  email = "youremail@domain.com"
  facebook = "username"
  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    identifier = "samples"
    name = "Samples"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Code Sample"
    url = "/post/2016-03-08-code-sample"

[[menu.main]]
    parent = "samples"
    name = "Test Markdown"
    url = "/post/2015-02-20-test-markdown"

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3